name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Gradle build
      run: ./gradlew assembleRelease
    - name: Sign artifact
      id: signArtifact
      uses: filippoLeporati93/android-release-signer@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        alias: ${{ secrets.KEYALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "35.0.0"
    - name: Move signed APK into place
      run: mv "${{steps.signArtifact.outputs.signedReleaseFile}}" app/build/outputs/apk/release/app-release.apk
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Signed release APK
        path: app/build/outputs/apk/release/app-release.apk
